import Mathlib

/-!
# Pólya enumeration, unweighted form

This file gives the fixed-coloring count behind the unweighted Pólya enumeration
formula, then applies Burnside's lemma from Mathlib.
-/

namespace AnalyticCombinatorics.Ch1.Polya

open scoped BigOperators

attribute [local instance] arrowAction

noncomputable local instance orbitRelDecidableRel {H X : Type*} [Group H] [MulAction H X] :
    DecidableRel (MulAction.orbitRel H X).r :=
  Classical.decRel _

noncomputable local instance subtypeFintypeClassical {X : Type*} [Fintype X] (p : X → Prop) :
    Fintype {x // p x} :=
  @Subtype.fintype X p (Classical.decPred p) inferInstance

section General

variable {G D C : Type*} [Group G] [MulAction G D] [Fintype D] [DecidableEq D] [Fintype C]

/-- A coloring fixed by `g` is the same thing as a function on the orbits of `⟨g⟩`. -/
noncomputable def fixedColoringEquiv (g : G) :
    {f : D → C // g • f = f} ≃
      (MulAction.orbitRel.Quotient (Subgroup.zpowers g) D → C) where
  toFun f q :=
    Quotient.liftOn' q f.1 fun a b hab => by
      rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff] at hab
      rcases hab with ⟨x, hx⟩
      have hxfix : (x : G) • f.1 = f.1 :=
        smul_eq_self_of_mem_zpowers x.2 f.2
      have hvalue := congr_fun hxfix a
      have hinv : (x : G)⁻¹ • a = b := by
        rw [← hx]
        simp [MulAction.subgroup_smul_def]
      change f.1 ((x : G)⁻¹ • a) = f.1 a at hvalue
      have hconst : f.1 b = f.1 a := by
        simpa [hinv] using hvalue
      exact hconst.symm
  invFun F :=
    ⟨fun d => F (Quotient.mk'' d), by
      funext d
      change F (Quotient.mk'' (g⁻¹ • d)) = F (Quotient.mk'' d)
      congr 1
      apply Quotient.sound'
      rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff]
      refine ⟨⟨g⁻¹, ?_⟩, ?_⟩
      · exact Subgroup.inv_mem (Subgroup.zpowers g) (Subgroup.mem_zpowers g)
      · simp [MulAction.subgroup_smul_def]⟩
  left_inv f := by
    ext d
    rfl
  right_inv F := by
    funext q
    induction q using Quotient.inductionOn'
    rfl

/-- Fixed colorings of `D` by `C` under `g` are counted by colors to the number of
orbits of the cyclic subgroup generated by `g`. -/
theorem card_fixedBy_colorings (g : G) :
    Fintype.card {f : D → C // g • f = f} =
      Fintype.card C ^ Fintype.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) D) := by
  classical
  rw [Fintype.card_congr (fixedColoringEquiv (G := G) (D := D) (C := C) g)]
  exact Fintype.card_fun

/-- The unweighted Pólya enumeration formula, in the natural-number form with
the group cardinality cleared. -/
theorem polya_card_orbits_mul_card_group [Fintype G] :
    Fintype.card (MulAction.orbitRel.Quotient G (D → C)) * Fintype.card G =
      ∑ g : G,
        Fintype.card C ^ Fintype.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) D) := by
  classical
  rw [← MulAction.sum_card_fixedBy_eq_card_orbits_mul_card_group G (D → C)]
  exact Finset.sum_congr rfl fun g _ => card_fixedBy_colorings (G := G) (D := D) (C := C) g

end General

section Necklaces

open Multiplicative

/-- The multiplicative wrapper of `ZMod n` acts on `ZMod n` by additive translation. -/
instance zmodTranslationMulAction (n : ℕ) : MulAction (Multiplicative (ZMod n)) (ZMod n) where
  smul k x := k.toAdd + x
  one_smul x := by
    change (0 : ZMod n) + x = x
    simp
  mul_smul k l x := by
    change (k.toAdd + l.toAdd) + x = k.toAdd + (l.toAdd + x)
    rw [add_assoc]

@[simp]
theorem zmodTranslation_smul (n : ℕ) (k x : ZMod n) :
    (Multiplicative.ofAdd k : Multiplicative (ZMod n)) • x = k + x :=
  rfl

@[simp]
theorem zmodTranslation_smul_toAdd (n : ℕ) (k : Multiplicative (ZMod n)) (x : ZMod n) :
    k • x = k.toAdd + x :=
  rfl

instance zmodTranslationIsPretransitive (n : ℕ) :
    MulAction.IsPretransitive (Multiplicative (ZMod n)) (ZMod n) where
  exists_smul_eq x y := by
    refine ⟨Multiplicative.ofAdd (y - x), ?_⟩
    simp [sub_eq_add_neg, add_comm]

instance zmodTranslationIsCancelSMul (n : ℕ) :
    IsCancelSMul (Multiplicative (ZMod n)) (ZMod n) where
  left_cancel' k x y h := by
    change k.toAdd + x = k.toAdd + y at h
    exact add_left_cancel h
  right_cancel' k l x h := by
    apply Multiplicative.toAdd.injective
    change k.toAdd + x = l.toAdd + x at h
    exact add_right_cancel h

/-- For the translation action of `Multiplicative (ZMod n)`, the orbits of the cyclic
subgroup generated by `k` are the cosets of the subgroup of additive multiples of `k`;
there are `gcd n k.val` of them. -/
theorem card_zmod_zpowers_orbitQuotient (n : ℕ) [NeZero n] (k : ZMod n) :
    Fintype.card
        (MulAction.orbitRel.Quotient (Subgroup.zpowers (Multiplicative.ofAdd k))
          (ZMod n)) =
      Nat.gcd n k.val := by
  classical
  have hn : 0 < n := Nat.pos_of_ne_zero (NeZero.ne n)
  let H : Subgroup (Multiplicative (ZMod n)) := Subgroup.zpowers (Multiplicative.ofAdd k)
  have hHcard : Nat.card H = n / Nat.gcd n k.val := by
    dsimp [H]
    rw [Nat.card_zpowers]
    change addOrderOf k = n / Nat.gcd n k.val
    rw [← ZMod.natCast_zmod_val k]
    simpa using (ZMod.addOrderOf_coe k.val (n := n) (NeZero.ne n))
  have hGcard : Nat.card (Multiplicative (ZMod n)) = n := by
    rw [Nat.card_eq_fintype_card, Fintype.card_multiplicative, ZMod.card]
  have hindex : H.index = Nat.gcd n k.val := by
    have hmul := H.card_mul_index
    rw [hHcard, hGcard] at hmul
    have hgpos : 0 < Nat.gcd n k.val := Nat.gcd_pos_of_pos_left k.val hn
    have hgle : Nat.gcd n k.val ≤ n :=
      Nat.le_of_dvd hn (Nat.gcd_dvd_left n k.val)
    have hdivpos : 0 < n / Nat.gcd n k.val := Nat.div_pos hgle hgpos
    have hdivmul : n / Nat.gcd n k.val * Nat.gcd n k.val = n :=
      Nat.div_mul_cancel (Nat.gcd_dvd_left n k.val)
    exact Nat.eq_of_mul_eq_mul_left hdivpos (hmul.trans hdivmul.symm)
  have hquot :
      Fintype.card (MulAction.orbitRel.Quotient H (ZMod n)) = H.index := by
    calc
      Fintype.card (MulAction.orbitRel.Quotient H (ZMod n)) =
          Fintype.card ((Multiplicative (ZMod n)) ⧸ H) :=
        Fintype.card_congr
          (MulAction.equivSubgroupOrbitsQuotientGroup
            (α := Multiplicative (ZMod n)) (β := ZMod n) (x := (0 : ZMod n)) H)
      _ = Nat.card ((Multiplicative (ZMod n)) ⧸ H) := by
        rw [Nat.card_eq_fintype_card]
      _ = H.index := by
        rw [← H.index_eq_card]
  simpa [H] using hquot.trans hindex

/-- Binary necklaces in the gcd form of the classical necklace formula. -/
theorem card_binary_necklaces_neZero (n : ℕ) [NeZero n] :
    Fintype.card
        (MulAction.orbitRel.Quotient (Multiplicative (ZMod n)) (ZMod n → Bool)) * n =
      ∑ k : ZMod n, 2 ^ Nat.gcd n k.val := by
  classical
  have hn : 0 < n := Nat.pos_of_ne_zero (NeZero.ne n)
  calc
    Fintype.card
          (MulAction.orbitRel.Quotient (Multiplicative (ZMod n)) (ZMod n → Bool)) * n =
        Fintype.card
          (MulAction.orbitRel.Quotient (Multiplicative (ZMod n)) (ZMod n → Bool)) *
            Fintype.card (Multiplicative (ZMod n)) := by
          rw [Fintype.card_multiplicative, ZMod.card]
    _ =
        ∑ g : Multiplicative (ZMod n),
          Fintype.card Bool ^
            Fintype.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) (ZMod n)) := by
          rw [polya_card_orbits_mul_card_group
            (G := Multiplicative (ZMod n)) (D := ZMod n) (C := Bool)]
    _ = ∑ k : ZMod n, 2 ^ Nat.gcd n k.val := by
      refine Fintype.sum_equiv Multiplicative.toAdd _ _ ?_
      intro g
      have hcard :
          Fintype.card (MulAction.orbitRel.Quotient (Subgroup.zpowers g) (ZMod n)) =
            Nat.gcd n g.toAdd.val := by
        simpa [ofAdd_toAdd] using
          card_zmod_zpowers_orbitQuotient (n := n) (k := g.toAdd)
      rw [Fintype.card_bool, hcard]

/-- Binary necklaces, with the positivity hypothesis as an ordinary argument. -/
theorem card_binary_necklaces (n : ℕ) (hn : 0 < n) :
    letI : NeZero n := ⟨Nat.ne_of_gt hn⟩
    Fintype.card
        (MulAction.orbitRel.Quotient (Multiplicative (ZMod n)) (ZMod n → Bool)) * n =
      ∑ k : ZMod n, 2 ^ Nat.gcd n k.val := by
  letI : NeZero n := ⟨Nat.ne_of_gt hn⟩
  exact card_binary_necklaces_neZero n

end Necklaces

end AnalyticCombinatorics.Ch1.Polya
