-- Analytic Combinatorics — Lean 4 Formalization
-- Flajolet & Sedgewick (2009)
-- github.com/xiangyazi24/AnalyticCombinatorics

-- ┌─────────────────────────────────────────┐
-- │  Part A: Symbolic Method                │
-- └─────────────────────────────────────────┘
import AnalyticCombinatorics.PartA.Ch1.CombinatorialClass
import AnalyticCombinatorics.PartA.Ch1.Sequences
import AnalyticCombinatorics.PartA.Ch1.Trees
import AnalyticCombinatorics.PartA.Ch1.PlaneTrees
import AnalyticCombinatorics.PartA.Ch1.MotzkinTrees
import AnalyticCombinatorics.PartA.Ch1.SchroederTheory
import AnalyticCombinatorics.PartA.Ch1.StringsTheory
import AnalyticCombinatorics.PartA.Ch1.WordPatterns
import AnalyticCombinatorics.PartA.Ch1.Newton
import AnalyticCombinatorics.PartA.Ch1.IntPartTheory
import AnalyticCombinatorics.PartA.Ch1.LatticePaths
import AnalyticCombinatorics.PartA.Ch1.Multiset
import AnalyticCombinatorics.PartA.Ch1.Powerset
import AnalyticCombinatorics.PartA.Ch1.Cycle
import AnalyticCombinatorics.PartA.Ch1.CatalanBijections
import AnalyticCombinatorics.PartA.Ch1.UnlabelledStructures
import AnalyticCombinatorics.PartA.Ch1.GeneralTrees
import AnalyticCombinatorics.PartA.Ch1.Necklaces
import AnalyticCombinatorics.PartA.Ch1.QAnalogs
import AnalyticCombinatorics.PartA.Ch1.SymbolicTransfer
import AnalyticCombinatorics.PartA.Ch1.CombinatorialIdentities
import AnalyticCombinatorics.PartA.Ch1.GFOperations
import AnalyticCombinatorics.PartA.Ch1.LagrangeInversion
import AnalyticCombinatorics.PartA.Ch1.GeneratingFunctions
import AnalyticCombinatorics.PartA.Ch1.WordsLanguages
import AnalyticCombinatorics.PartA.Ch1.PlanarMaps
import AnalyticCombinatorics.PartA.Ch1.FunctionalEquations
import AnalyticCombinatorics.PartA.Ch1.IntegerCompositions
import AnalyticCombinatorics.PartA.Ch1.PolynomialMethods
import AnalyticCombinatorics.PartA.Ch1.ContinuedFractions
import AnalyticCombinatorics.PartA.Ch1.SymbolicMethodAdvanced
import AnalyticCombinatorics.PartA.Ch1.OGFCoefficients
import AnalyticCombinatorics.PartA.Ch1.SpeciesTheory
import AnalyticCombinatorics.PartA.Ch1.InversionFormulas
import AnalyticCombinatorics.PartA.Ch1.AnalyticInversion
import AnalyticCombinatorics.PartA.Ch1.Polyominoes
import AnalyticCombinatorics.PartA.Ch1.PermutationEnumeration
import AnalyticCombinatorics.PartA.Ch1.EnumerativeGeometry
import AnalyticCombinatorics.PartA.Ch1.SetPartitions
import AnalyticCombinatorics.PartA.Ch1.SurjectionsStirling
import AnalyticCombinatorics.PartA.Ch1.GraphTheory
import AnalyticCombinatorics.PartA.Ch1.BinomialTransforms
import AnalyticCombinatorics.PartA.Ch1.Surjections2
import AnalyticCombinatorics.PartA.Ch1.MotzkinPaths
import AnalyticCombinatorics.PartA.Ch1.FibonacciIdentities
import AnalyticCombinatorics.PartA.Ch1.DerangementVariants
import AnalyticCombinatorics.PartA.Ch1.BinaryTreeShapes
import AnalyticCombinatorics.PartA.Ch1.PermutationCycleIndex
import AnalyticCombinatorics.PartA.Ch1.GFClosure
import AnalyticCombinatorics.PartA.Ch1.PartitionIdentities
import AnalyticCombinatorics.PartA.Ch1.SymmetricFunctions
import AnalyticCombinatorics.PartA.Ch1.WordCombinatorics
import AnalyticCombinatorics.PartA.Ch1.PolyominoEnumeration
import AnalyticCombinatorics.PartA.Ch2.PermutationCycles
import AnalyticCombinatorics.PartA.Ch2.LabelledClass
import AnalyticCombinatorics.PartA.Ch2.LabelledTrees
import AnalyticCombinatorics.PartA.Ch2.Surjections
import AnalyticCombinatorics.PartA.Ch2.Derangements
import AnalyticCombinatorics.PartA.Ch2.BellNumbers
import AnalyticCombinatorics.PartA.Ch2.Involutions
import AnalyticCombinatorics.PartA.Ch2.CycleIndex
import AnalyticCombinatorics.PartA.Ch2.RestrictedPerms
import AnalyticCombinatorics.PartA.Ch2.ExponentialFormula
import AnalyticCombinatorics.PartA.Ch2.SetCycleOps
import AnalyticCombinatorics.PartA.Ch2.Species
import AnalyticCombinatorics.PartA.Ch2.ParkingFunctions
import AnalyticCombinatorics.PartA.Ch2.AlternatingPerms
import AnalyticCombinatorics.PartA.Ch2.RandomMappings
import AnalyticCombinatorics.PartA.Ch2.AnalyticNumberTheory
import AnalyticCombinatorics.PartA.Ch2.SpecialNumbers
import AnalyticCombinatorics.PartA.Ch2.UrnsOccupancy
import AnalyticCombinatorics.PartA.Ch2.GraphEnumeration
import AnalyticCombinatorics.PartA.Ch2.PermutationGroups
import AnalyticCombinatorics.PartA.Ch2.MapEnumeration
import AnalyticCombinatorics.PartA.Ch2.NumberTheoreticGF
import AnalyticCombinatorics.PartA.Ch2.ExponentialStructures
import AnalyticCombinatorics.PartA.Ch2.OrderedStructures
import AnalyticCombinatorics.PartA.Ch2.DesignTheory
import AnalyticCombinatorics.PartA.Ch2.CombinatoricsBounds
import AnalyticCombinatorics.PartA.Ch2.SymmetricFunctions
import AnalyticCombinatorics.PartA.Ch2.LatinSquares
import AnalyticCombinatorics.PartA.Ch2.HarmonicNumbers
import AnalyticCombinatorics.PartA.Ch2.CombinatoricsOnGraphs
import AnalyticCombinatorics.PartA.Ch2.CodingTheory
import AnalyticCombinatorics.PartA.Ch2.PermutationInversions
import AnalyticCombinatorics.PartA.Ch2.ConnectedComponents
import AnalyticCombinatorics.PartA.Ch2.TableauxPartitions
import AnalyticCombinatorics.PartA.Ch2.PermutationDescents
import AnalyticCombinatorics.PartA.Ch2.PartitionLattice
import AnalyticCombinatorics.PartA.Ch2.EGFApplications
import AnalyticCombinatorics.PartA.Ch2.YoungTableaux
import AnalyticCombinatorics.PartA.Ch2.FunctionalDigraphs
import AnalyticCombinatorics.PartA.Ch2.PermutationFixedPoints
import AnalyticCombinatorics.PartA.Ch2.SpeciesTheory
import AnalyticCombinatorics.PartA.Ch2.ExponentialStructures
import AnalyticCombinatorics.PartA.Ch2.PermutationGroups
import AnalyticCombinatorics.PartA.Ch2.ConnectedStructures
import AnalyticCombinatorics.PartA.Ch3.Parameters
import AnalyticCombinatorics.PartA.Ch3.MultivariateGF
import AnalyticCombinatorics.PartA.Ch3.PermutationRuns
import AnalyticCombinatorics.PartA.Ch3.Moments
import AnalyticCombinatorics.PartA.Ch3.LimitLaws
import AnalyticCombinatorics.PartA.Ch3.PermutationStatistics
import AnalyticCombinatorics.PartA.Ch3.ProbabilityGF
import AnalyticCombinatorics.PartA.Ch3.CombinatoricsOnWords
import AnalyticCombinatorics.PartA.Ch3.CentralLimitTheorems
import AnalyticCombinatorics.PartA.Ch3.LatticePathMethods
import AnalyticCombinatorics.PartA.Ch3.PatternAvoidance
import AnalyticCombinatorics.PartA.Ch3.PermutationPatterns
import AnalyticCombinatorics.PartA.Ch3.CombOptimization
import AnalyticCombinatorics.PartA.Ch3.WalksCounting
import AnalyticCombinatorics.PartA.Ch3.RecurrenceAnalysis
import AnalyticCombinatorics.PartA.Ch3.SpecialSequences
import AnalyticCombinatorics.PartA.Ch3.DigitalCombinatorics
import AnalyticCombinatorics.PartA.Ch3.TreeStatistics
import AnalyticCombinatorics.PartA.Ch3.AsymptoticNotation
import AnalyticCombinatorics.PartA.Ch3.GeneratingFunctionOps
import AnalyticCombinatorics.PartA.Ch3.AnalyticMethods
import AnalyticCombinatorics.PartA.Ch3.ProbabilityDistributions
import AnalyticCombinatorics.PartA.Ch3.PatternAvoidanceAdvanced
import AnalyticCombinatorics.PartA.Ch3.BoltzmannSampling
import AnalyticCombinatorics.PartA.Ch3.QueueingCombinatorics
import AnalyticCombinatorics.PartA.Ch3.TreeHeightDistribution
import AnalyticCombinatorics.PartA.Ch3.MomentGeneratingFunctions
import AnalyticCombinatorics.PartA.Ch3.SymbolicMethodIII
import AnalyticCombinatorics.PartA.Ch3.AnalyticDepoissonization
import AnalyticCombinatorics.PartA.Ch3.CumulantMethods
import AnalyticCombinatorics.PartA.Ch3.AsymptoticTransfers
import AnalyticCombinatorics.PartA.Ch3.ConcentrationInequalities
import AnalyticCombinatorics.PartA.Ch3.GaussianLimitLaws

-- ┌─────────────────────────────────────────┐
-- │  Part B: Complex Asymptotics            │
-- └─────────────────────────────────────────┘
import AnalyticCombinatorics.PartB.Ch4.GeneratingFunctionIdentities
import AnalyticCombinatorics.PartB.Ch4.RationalGF
import AnalyticCombinatorics.PartB.Ch4.MeromorphicCoeff
import AnalyticCombinatorics.PartB.Ch4.FormalPowerSeries
import AnalyticCombinatorics.PartB.Ch4.ComplexAnalysisBasics
import AnalyticCombinatorics.PartB.Ch4.AnalyticContinuation
import AnalyticCombinatorics.PartB.Ch4.AsymptoticExpansions
import AnalyticCombinatorics.PartB.Ch4.RecurrenceRelations
import AnalyticCombinatorics.PartB.Ch4.GFTransforms
import AnalyticCombinatorics.PartB.Ch4.StirlingApproximations
import AnalyticCombinatorics.PartB.Ch4.TauberianTheorems
import AnalyticCombinatorics.PartB.Ch4.MatrixMethods
import AnalyticCombinatorics.PartB.Ch4.OrdinaryGFApplications
import AnalyticCombinatorics.PartB.Ch4.LinearRecurrences
import AnalyticCombinatorics.PartB.Ch4.CauchyIntegral
import AnalyticCombinatorics.PartB.Ch4.ExponentialGrowth
import AnalyticCombinatorics.PartB.Ch4.PartialFractions
import AnalyticCombinatorics.PartB.Ch4.AsymptoticSeries
import AnalyticCombinatorics.PartB.Ch4.ComplexVariables
import AnalyticCombinatorics.PartB.Ch4.RationalFunctionDecomposition
import AnalyticCombinatorics.PartB.Ch4.NumberTheoreticGF2
import AnalyticCombinatorics.PartB.Ch4.SingularityAnalysisBasics
import AnalyticCombinatorics.PartB.Ch4.CoefficientExtractionMethods
import AnalyticCombinatorics.PartB.Ch4.ExponentialGFCoefficients
import AnalyticCombinatorics.PartB.Ch4.RadiusOfConvergence
import AnalyticCombinatorics.PartB.Ch4.AlgebraicGF
import AnalyticCombinatorics.PartB.Ch4.MeromorphicGF
import AnalyticCombinatorics.PartB.Ch4.TransferTheoremsII
import AnalyticCombinatorics.PartB.Ch4.PeriodicCoefficients
import AnalyticCombinatorics.PartB.Ch4.SupAperiodicGF
import AnalyticCombinatorics.PartB.Ch5.CompositionsAsymptotics
import AnalyticCombinatorics.PartB.Ch5.AsymptoticEnumeration
import AnalyticCombinatorics.PartB.Ch5.CoefficientAsymptotics
import AnalyticCombinatorics.PartB.Ch5.DigitalAnalysis
import AnalyticCombinatorics.PartB.Ch5.DigitalTrees
import AnalyticCombinatorics.PartB.Ch5.ContextFreeGrammars
import AnalyticCombinatorics.PartB.Ch5.SpecialFunctions
import AnalyticCombinatorics.PartB.Ch5.HypergeometricFunctions
import AnalyticCombinatorics.PartB.Ch5.ResidueCalculus
import AnalyticCombinatorics.PartB.Ch5.AnalyticNumberTheory2
import AnalyticCombinatorics.PartB.Ch5.AnalyticNumberTheory3
import AnalyticCombinatorics.PartB.Ch5.FiniteAutomata
import AnalyticCombinatorics.PartB.Ch5.GFConvergence
import AnalyticCombinatorics.PartB.Ch5.SeriesAcceleration
import AnalyticCombinatorics.PartB.Ch5.PolynomialArithmetic
import AnalyticCombinatorics.PartB.Ch5.BijectionPrinciples
import AnalyticCombinatorics.PartB.Ch5.AutomataEnumeration
import AnalyticCombinatorics.PartB.Ch5.OrdinaryDifferentialEquations
import AnalyticCombinatorics.PartB.Ch5.MellinTransforms
import AnalyticCombinatorics.PartB.Ch5.FunctionalEquations2
import AnalyticCombinatorics.PartB.Ch5.DFactorial
import AnalyticCombinatorics.PartB.Ch5.AnalyticContinuation
import AnalyticCombinatorics.PartB.Ch5.SteepestDescent
import AnalyticCombinatorics.PartB.Ch5.RiemannZetaValues
import AnalyticCombinatorics.PartB.Ch5.AsymptoticsOfSums
import AnalyticCombinatorics.PartB.Ch5.GeneratingFunctionAnalyticity
import AnalyticCombinatorics.PartB.Ch5.SingularInversion
import AnalyticCombinatorics.PartB.Ch5.DirichletSeries
import AnalyticCombinatorics.PartB.Ch5.EulerMaclaurin
import AnalyticCombinatorics.PartB.Ch5.AnalyticNumberTheory
import AnalyticCombinatorics.PartB.Ch5.ContourIntegration
import AnalyticCombinatorics.PartB.Ch6.MellinHarmonicSums
import AnalyticCombinatorics.PartB.Ch6.SingularityAnalysis
import AnalyticCombinatorics.PartB.Ch6.AlgebraicSingularity
import AnalyticCombinatorics.PartB.Ch6.Asymptotics
import AnalyticCombinatorics.PartB.Ch6.DeltaDomain
import AnalyticCombinatorics.PartB.Ch6.TransferTheorems
import AnalyticCombinatorics.PartB.Ch6.PartitionAsymptotics
import AnalyticCombinatorics.PartB.Ch6.SingularityTypes
import AnalyticCombinatorics.PartB.Ch6.AsymptoticMethods
import AnalyticCombinatorics.PartB.Ch6.EulerMaclaurin
import AnalyticCombinatorics.PartB.Ch6.CoefficientBounds
import AnalyticCombinatorics.PartB.Ch6.Asymptotics2F1
import AnalyticCombinatorics.PartB.Ch6.SingularityClassification
import AnalyticCombinatorics.PartB.Ch6.AsymptoticTransfer
import AnalyticCombinatorics.PartB.Ch6.LogarithmicSingularities
import AnalyticCombinatorics.PartB.Ch6.AnalyticInversion
import AnalyticCombinatorics.PartB.Ch6.CatalanAsymptotics2
import AnalyticCombinatorics.PartB.Ch6.GrowthRateClassification
import AnalyticCombinatorics.PartB.Ch6.TransferApplications
import AnalyticCombinatorics.PartB.Ch6.CoefficientTransferTheorems
import AnalyticCombinatorics.PartB.Ch6.MultiplicativeArithmetic
import AnalyticCombinatorics.PartB.Ch6.AlgebraicFunctionCoefficients
import AnalyticCombinatorics.PartB.Ch6.SaddlePointCoefficients
import AnalyticCombinatorics.PartB.Ch6.UniformAsymptotics
import AnalyticCombinatorics.PartB.Ch6.SubexponentialSequences
import AnalyticCombinatorics.PartB.Ch6.Asymptotics2F1Methods
import AnalyticCombinatorics.PartB.Ch6.DiagonalCoefficients
import AnalyticCombinatorics.PartB.Ch6.AlgebraicSingularities
import AnalyticCombinatorics.PartB.Ch6.CoefficientAsymptoticsII
import AnalyticCombinatorics.PartB.Ch6.MultiplicativeFunctions
import AnalyticCombinatorics.PartB.Ch7.CatalanAsymptotics
import AnalyticCombinatorics.PartB.Ch7.ApplicationsOfSingularity
import AnalyticCombinatorics.PartB.Ch7.TreeEnumeration
import AnalyticCombinatorics.PartB.Ch7.AnalyticInequalities
import AnalyticCombinatorics.PartB.Ch7.AsymptoticSeries
import AnalyticCombinatorics.PartB.Ch7.ExponentialGrowth
import AnalyticCombinatorics.PartB.Ch7.SubexponentialGrowth
import AnalyticCombinatorics.PartB.Ch7.MapAsymptotics
import AnalyticCombinatorics.PartB.Ch7.PartitionEnumeration
import AnalyticCombinatorics.PartB.Ch7.PermutationAsymptotics
import AnalyticCombinatorics.PartB.Ch7.AlgebraicFunctions
import AnalyticCombinatorics.PartB.Ch7.CombinatoricalSchemes
import AnalyticCombinatorics.PartB.Ch7.ImplicitFunctions
import AnalyticCombinatorics.PartB.Ch7.SmoothSchemes
import AnalyticCombinatorics.PartB.Ch7.InverseFunctions
import AnalyticCombinatorics.PartB.Ch7.ContextFreeSchemes
import AnalyticCombinatorics.PartB.Ch7.NewtonPolygon
import AnalyticCombinatorics.PartB.Ch7.PolygonTriangulations
import AnalyticCombinatorics.PartB.Ch7.AsymptoticExpansionSchemes
import AnalyticCombinatorics.PartB.Ch7.SimpleTreeFamilies
import AnalyticCombinatorics.PartB.Ch7.PolyaTreeEnumeration
import AnalyticCombinatorics.PartB.Ch7.TreeHeightAsymptotics
import AnalyticCombinatorics.PartB.Ch7.FunctionalGraphs
import AnalyticCombinatorics.PartB.Ch7.AnalyticInversionApplications
import AnalyticCombinatorics.PartB.Ch7.RecursiveTreeStructures
import AnalyticCombinatorics.PartB.Ch7.PowerSeriesComposition
import AnalyticCombinatorics.PartB.Ch7.ImplicitFunctionCoefficients
import AnalyticCombinatorics.PartB.Ch7.CriticalExponents
import AnalyticCombinatorics.PartB.Ch7.SchroederPaths
import AnalyticCombinatorics.PartB.Ch7.SingularInversion2
import AnalyticCombinatorics.PartB.Ch8.SaddlePoint
import AnalyticCombinatorics.PartB.Ch8.SaddlePointApps
import AnalyticCombinatorics.PartB.Ch8.MultivariateSaddlePoint
import AnalyticCombinatorics.PartB.Ch8.QueueTheory
import AnalyticCombinatorics.PartB.Ch8.AlgorithmicComplexity
import AnalyticCombinatorics.PartB.Ch8.SaddlePointExamples
import AnalyticCombinatorics.PartB.Ch8.LaplaceMethod
import AnalyticCombinatorics.PartB.Ch8.CombinatoricsBoundsB
import AnalyticCombinatorics.PartB.Ch8.IntegerPartitionBounds
import AnalyticCombinatorics.PartB.Ch8.CentralLimitSaddlePoint
import AnalyticCombinatorics.PartB.Ch8.GaussianApproximation
import AnalyticCombinatorics.PartB.Ch8.PermutationSaddlePoint
import AnalyticCombinatorics.PartB.Ch8.AsymptoticEnumeration2
import AnalyticCombinatorics.PartB.Ch8.StirlingApproximation
import AnalyticCombinatorics.PartB.Ch8.LargeDeviations
import AnalyticCombinatorics.PartB.Ch8.SaddlePointPartitions
import AnalyticCombinatorics.PartB.Ch8.MomentMethods
import AnalyticCombinatorics.PartB.Ch8.ConcentrationInequalities
import AnalyticCombinatorics.PartB.Ch8.ExponentialIntegrals
import AnalyticCombinatorics.PartB.Ch8.GammaFunctionProperties
import AnalyticCombinatorics.PartB.Ch8.PermutationStatisticsAsymptotics
import AnalyticCombinatorics.PartB.Ch8.IntegerPartitionAsymptotics
import AnalyticCombinatorics.PartB.Ch8.QueueingAsymptotics
import AnalyticCombinatorics.PartB.Ch8.AsymptoticExpansionMethods
import AnalyticCombinatorics.PartB.Ch8.CombinatoricsBoundsC
import AnalyticCombinatorics.PartB.Ch8.MellinTransformAsymptotics
import AnalyticCombinatorics.PartB.Ch8.ExtremeValueDistributions
import AnalyticCombinatorics.PartB.Ch8.PoissonApproximation
import AnalyticCombinatorics.PartB.Ch8.StirlingSaddlePoint
import AnalyticCombinatorics.PartB.Ch8.DistributionApproximation
import AnalyticCombinatorics.PartB.Ch8.ExponentialTailBounds
import AnalyticCombinatorics.PartB.Ch9.RandomStructures
import AnalyticCombinatorics.PartB.Ch9.RandomGraphs
import AnalyticCombinatorics.PartB.Ch9.Depoissonization
import AnalyticCombinatorics.PartB.Ch9.LargePowers
import AnalyticCombinatorics.PartB.Ch9.RandomAllocations
import AnalyticCombinatorics.PartB.Ch9.PolyaEnumeration
import AnalyticCombinatorics.PartB.Ch9.EntropyInformation
import AnalyticCombinatorics.PartB.Ch9.RandomPermutations
import AnalyticCombinatorics.PartB.Ch9.PhaseTransitions
import AnalyticCombinatorics.PartB.Ch9.RandomTreeStatistics
import AnalyticCombinatorics.PartB.Ch9.LimitDistributions
import AnalyticCombinatorics.PartB.Ch9.ProbabilisticMethod
import AnalyticCombinatorics.PartB.Ch9.HashingAnalysis
import AnalyticCombinatorics.PartB.Ch9.BranchingProcesses
import AnalyticCombinatorics.PartB.Ch9.UrnsAndBalls
import AnalyticCombinatorics.PartB.Ch9.RandomTrees
import AnalyticCombinatorics.PartB.Ch9.RandomPermutationCycles
import AnalyticCombinatorics.PartB.Ch9.CouponCollector
import AnalyticCombinatorics.PartB.Ch9.RandomGraphProperties
import AnalyticCombinatorics.PartB.Ch9.ProbabilisticCounting
import AnalyticCombinatorics.PartB.Ch9.ExtremalGraphCombinatorics
import AnalyticCombinatorics.PartB.Ch9.AnalyticUrns
import AnalyticCombinatorics.PartB.Ch9.StringCombinatorics
import AnalyticCombinatorics.PartB.Ch9.RandomGraphThresholds
import AnalyticCombinatorics.PartB.Ch9.BirthdayParadoxVariants
import AnalyticCombinatorics.PartB.Ch9.SearchTreeAnalysis
import AnalyticCombinatorics.PartB.Ch9.QueueingNetworks
import AnalyticCombinatorics.PartB.Ch9.DigitalTreeAnalysis

-- ┌─────────────────────────────────────────┐
-- │  Examples (build individually)          │
-- └─────────────────────────────────────────┘
-- Examples define standalone types that conflict with theory files.
-- Build with: lake build AnalyticCombinatorics.Examples.<Name>
