-- Analytic Combinatorics — Lean 4 Formalization
-- Flajolet & Sedgewick (2009)
-- github.com/xiangyazi24/AnalyticCombinatorics

-- ┌─────────────────────────────────────────┐
-- │  Part A: Symbolic Method                │
-- └─────────────────────────────────────────┘
import AnalyticCombinatorics.PartA.Ch1.CombinatorialClass
import AnalyticCombinatorics.PartA.Ch1.Sequences
import AnalyticCombinatorics.PartA.Ch1.Trees
import AnalyticCombinatorics.PartA.Ch1.PlaneTrees
import AnalyticCombinatorics.PartA.Ch1.MotzkinTrees
import AnalyticCombinatorics.PartA.Ch1.SchroederTheory
import AnalyticCombinatorics.PartA.Ch1.StringsTheory
import AnalyticCombinatorics.PartA.Ch1.WordPatterns
import AnalyticCombinatorics.PartA.Ch1.Newton
import AnalyticCombinatorics.PartA.Ch1.IntPartTheory
import AnalyticCombinatorics.PartA.Ch1.LatticePaths
import AnalyticCombinatorics.PartA.Ch1.Multiset
import AnalyticCombinatorics.PartA.Ch1.Powerset
import AnalyticCombinatorics.PartA.Ch1.Cycle
import AnalyticCombinatorics.PartA.Ch1.CatalanBijections
import AnalyticCombinatorics.PartA.Ch1.UnlabelledStructures
import AnalyticCombinatorics.PartA.Ch1.GeneralTrees
import AnalyticCombinatorics.PartA.Ch1.Necklaces
import AnalyticCombinatorics.PartA.Ch1.QAnalogs
import AnalyticCombinatorics.PartA.Ch1.SymbolicTransfer
import AnalyticCombinatorics.PartA.Ch1.CombinatorialIdentities
import AnalyticCombinatorics.PartA.Ch1.GFOperations
import AnalyticCombinatorics.PartA.Ch1.LagrangeInversion
import AnalyticCombinatorics.PartA.Ch1.GeneratingFunctions
import AnalyticCombinatorics.PartA.Ch1.WordsLanguages
import AnalyticCombinatorics.PartA.Ch1.PlanarMaps
import AnalyticCombinatorics.PartA.Ch1.FunctionalEquations
import AnalyticCombinatorics.PartA.Ch1.IntegerCompositions
import AnalyticCombinatorics.PartA.Ch1.PolynomialMethods
import AnalyticCombinatorics.PartA.Ch1.ContinuedFractions
import AnalyticCombinatorics.PartA.Ch1.SymbolicMethodAdvanced
import AnalyticCombinatorics.PartA.Ch1.OGFCoefficients
import AnalyticCombinatorics.PartA.Ch1.SpeciesTheory
import AnalyticCombinatorics.PartA.Ch1.InversionFormulas
import AnalyticCombinatorics.PartA.Ch1.AnalyticInversion
import AnalyticCombinatorics.PartA.Ch1.Polyominoes
import AnalyticCombinatorics.PartA.Ch1.PermutationEnumeration
import AnalyticCombinatorics.PartA.Ch2.PermutationCycles
import AnalyticCombinatorics.PartA.Ch2.LabelledClass
import AnalyticCombinatorics.PartA.Ch2.LabelledTrees
import AnalyticCombinatorics.PartA.Ch2.Surjections
import AnalyticCombinatorics.PartA.Ch2.Derangements
import AnalyticCombinatorics.PartA.Ch2.BellNumbers
import AnalyticCombinatorics.PartA.Ch2.Involutions
import AnalyticCombinatorics.PartA.Ch2.CycleIndex
import AnalyticCombinatorics.PartA.Ch2.RestrictedPerms
import AnalyticCombinatorics.PartA.Ch2.ExponentialFormula
import AnalyticCombinatorics.PartA.Ch2.SetCycleOps
import AnalyticCombinatorics.PartA.Ch2.Species
import AnalyticCombinatorics.PartA.Ch2.ParkingFunctions
import AnalyticCombinatorics.PartA.Ch2.AlternatingPerms
import AnalyticCombinatorics.PartA.Ch2.RandomMappings
import AnalyticCombinatorics.PartA.Ch2.AnalyticNumberTheory
import AnalyticCombinatorics.PartA.Ch2.SpecialNumbers
import AnalyticCombinatorics.PartA.Ch2.UrnsOccupancy
import AnalyticCombinatorics.PartA.Ch2.GraphEnumeration
import AnalyticCombinatorics.PartA.Ch2.PermutationGroups
import AnalyticCombinatorics.PartA.Ch2.MapEnumeration
import AnalyticCombinatorics.PartA.Ch2.NumberTheoreticGF
import AnalyticCombinatorics.PartA.Ch2.ExponentialStructures
import AnalyticCombinatorics.PartA.Ch2.OrderedStructures
import AnalyticCombinatorics.PartA.Ch2.DesignTheory
import AnalyticCombinatorics.PartA.Ch2.CombinatoricsBounds
import AnalyticCombinatorics.PartA.Ch2.SymmetricFunctions
import AnalyticCombinatorics.PartA.Ch2.LatinSquares
import AnalyticCombinatorics.PartA.Ch2.HarmonicNumbers
import AnalyticCombinatorics.PartA.Ch3.Parameters
import AnalyticCombinatorics.PartA.Ch3.MultivariateGF
import AnalyticCombinatorics.PartA.Ch3.PermutationRuns
import AnalyticCombinatorics.PartA.Ch3.Moments
import AnalyticCombinatorics.PartA.Ch3.LimitLaws
import AnalyticCombinatorics.PartA.Ch3.PermutationStatistics
import AnalyticCombinatorics.PartA.Ch3.ProbabilityGF
import AnalyticCombinatorics.PartA.Ch3.CombinatoricsOnWords
import AnalyticCombinatorics.PartA.Ch3.CentralLimitTheorems
import AnalyticCombinatorics.PartA.Ch3.LatticePathMethods
import AnalyticCombinatorics.PartA.Ch3.PatternAvoidance
import AnalyticCombinatorics.PartA.Ch3.PermutationPatterns
import AnalyticCombinatorics.PartA.Ch3.CombOptimization
import AnalyticCombinatorics.PartA.Ch3.WalksCounting
import AnalyticCombinatorics.PartA.Ch3.RecurrenceAnalysis

-- ┌─────────────────────────────────────────┐
-- │  Part B: Complex Asymptotics            │
-- └─────────────────────────────────────────┘
import AnalyticCombinatorics.PartB.Ch4.RationalGF
import AnalyticCombinatorics.PartB.Ch4.MeromorphicCoeff
import AnalyticCombinatorics.PartB.Ch4.FormalPowerSeries
import AnalyticCombinatorics.PartB.Ch4.ComplexAnalysisBasics
import AnalyticCombinatorics.PartB.Ch4.AnalyticContinuation
import AnalyticCombinatorics.PartB.Ch4.AsymptoticExpansions
import AnalyticCombinatorics.PartB.Ch4.RecurrenceRelations
import AnalyticCombinatorics.PartB.Ch4.GFTransforms
import AnalyticCombinatorics.PartB.Ch4.StirlingApproximations
import AnalyticCombinatorics.PartB.Ch4.TauberianTheorems
import AnalyticCombinatorics.PartB.Ch4.MatrixMethods
import AnalyticCombinatorics.PartB.Ch5.CompositionsAsymptotics
import AnalyticCombinatorics.PartB.Ch5.AsymptoticEnumeration
import AnalyticCombinatorics.PartB.Ch5.CoefficientAsymptotics
import AnalyticCombinatorics.PartB.Ch5.DigitalAnalysis
import AnalyticCombinatorics.PartB.Ch5.DigitalTrees
import AnalyticCombinatorics.PartB.Ch5.ContextFreeGrammars
import AnalyticCombinatorics.PartB.Ch5.SpecialFunctions
import AnalyticCombinatorics.PartB.Ch5.HypergeometricFunctions
import AnalyticCombinatorics.PartB.Ch5.ResidueCalculus
import AnalyticCombinatorics.PartB.Ch5.AnalyticNumberTheory2
import AnalyticCombinatorics.PartB.Ch5.FiniteAutomata
import AnalyticCombinatorics.PartB.Ch5.GFConvergence
import AnalyticCombinatorics.PartB.Ch6.MellinHarmonicSums
import AnalyticCombinatorics.PartB.Ch6.SingularityAnalysis
import AnalyticCombinatorics.PartB.Ch6.AlgebraicSingularity
import AnalyticCombinatorics.PartB.Ch6.Asymptotics
import AnalyticCombinatorics.PartB.Ch6.DeltaDomain
import AnalyticCombinatorics.PartB.Ch6.TransferTheorems
import AnalyticCombinatorics.PartB.Ch6.PartitionAsymptotics
import AnalyticCombinatorics.PartB.Ch6.SingularityTypes
import AnalyticCombinatorics.PartB.Ch6.AsymptoticMethods
import AnalyticCombinatorics.PartB.Ch6.EulerMaclaurin
import AnalyticCombinatorics.PartB.Ch6.CoefficientBounds
import AnalyticCombinatorics.PartB.Ch6.Asymptotics2F1
import AnalyticCombinatorics.PartB.Ch7.CatalanAsymptotics
import AnalyticCombinatorics.PartB.Ch7.ApplicationsOfSingularity
import AnalyticCombinatorics.PartB.Ch7.TreeEnumeration
import AnalyticCombinatorics.PartB.Ch7.AnalyticInequalities
import AnalyticCombinatorics.PartB.Ch7.AsymptoticSeries
import AnalyticCombinatorics.PartB.Ch7.ExponentialGrowth
import AnalyticCombinatorics.PartB.Ch7.SubexponentialGrowth
import AnalyticCombinatorics.PartB.Ch8.SaddlePoint
import AnalyticCombinatorics.PartB.Ch8.SaddlePointApps
import AnalyticCombinatorics.PartB.Ch8.MultivariateSaddlePoint
import AnalyticCombinatorics.PartB.Ch8.QueueTheory
import AnalyticCombinatorics.PartB.Ch8.AlgorithmicComplexity
import AnalyticCombinatorics.PartB.Ch8.SaddlePointExamples
import AnalyticCombinatorics.PartB.Ch8.LaplaceMethod
import AnalyticCombinatorics.PartB.Ch9.RandomStructures
import AnalyticCombinatorics.PartB.Ch9.RandomGraphs
import AnalyticCombinatorics.PartB.Ch9.Depoissonization
import AnalyticCombinatorics.PartB.Ch9.LargePowers
import AnalyticCombinatorics.PartB.Ch9.RandomAllocations
import AnalyticCombinatorics.PartB.Ch9.PolyaEnumeration
import AnalyticCombinatorics.PartB.Ch9.EntropyInformation
import AnalyticCombinatorics.PartB.Ch9.RandomPermutations
import AnalyticCombinatorics.PartB.Ch9.PhaseTransitions
import AnalyticCombinatorics.PartB.Ch9.RandomTreeStatistics
import AnalyticCombinatorics.PartB.Ch9.LimitDistributions

-- ┌─────────────────────────────────────────┐
-- │  Examples (build individually)          │
-- └─────────────────────────────────────────┘
-- Examples define standalone types that conflict with theory files.
-- Build with: lake build AnalyticCombinatorics.Examples.<Name>
