import Mathlib.Tactic

set_option linter.style.nativeDecide false

namespace AnalyticCombinatorics.PartB.Ch5.DFactorial


open Finset

/-!
Chapter V style sanity checks for D-finite, also called holonomic or
P-recursive, sequences.

The formal definition below uses integer-valued sequences and polynomial
coefficient functions `p_j : Nat -> Int`.  The list of concrete examples is
kept computational: each stated identity is verified by `native_decide` on a
finite initial range.
-/

abbrev Sequence := Nat -> Int
abbrev Polynomial := Nat -> Int

/-- The value of `sum_j p_j(n) a(n+j)` for an order-`d` recurrence. -/
def pRecurrenceValue (d : Nat) (p : Fin (d + 1) -> Polynomial)
    (a : Sequence) (n : Nat) : Int :=
  ∑ j : Fin (d + 1), p j n * a (n + j.val)

/--
A P-recursive sequence satisfies
`p_d(n) * a(n+d) + ... + p_0(n) * a(n) = 0`
with a nonzero leading coefficient.
-/
def PRecursive (a : Sequence) : Prop :=
  ∃ d : Nat, ∃ p : Fin (d + 1) -> Polynomial,
    (∃ n : Nat, p ⟨d, Nat.lt_succ_self d⟩ n ≠ 0) ∧
      ∀ n : Nat, pRecurrenceValue d p a n = 0

abbrev DFinite := PRecursive

/-- Finite computational check for a P-recursive certificate. -/
def pRecurrenceHoldsOnRange (N d : Nat) (p : Fin (d + 1) -> Polynomial)
    (a : Sequence) : Bool :=
  (List.range N).all (fun n => decide (pRecurrenceValue d p a n = 0))

/-! ## Catalan numbers -/

/-- Catalan number `C_n = binom(2n,n)/(n+1)`. -/
def catalan (n : Nat) : Nat :=
  Nat.choose (2 * n) n / (n + 1)

def catalanSeq : Sequence := fun n => catalan n

/-- Coefficients for `(n+2) C(n+1) - (4n+2) C(n) = 0`. -/
def catalanP : Fin 2 -> Polynomial := fun j n =>
  let x : Int := n
  match j.val with
  | 0 => -((4 : Int) * x + 2)
  | _ => x + 2

def catalanRecurrenceAt (n : Nat) : Bool :=
  ((n : Int) + 2) * catalanSeq (n + 1) ==
    ((4 : Int) * (n : Int) + 2) * catalanSeq n

/-- Catalan recurrence check for `n = 0..6`. -/
theorem catalan_recurrence_check_0_to_6 :
    (List.range 7).all catalanRecurrenceAt = true := by
  native_decide

/-- Same Catalan check through the generic P-recursive evaluator. -/
theorem catalan_precursive_check_0_to_6 :
    pRecurrenceHoldsOnRange 7 1 catalanP catalanSeq = true := by
  native_decide

/-! ## Fibonacci numbers -/

/-- Fibonacci numbers with `F(0)=0`, `F(1)=1`. -/
def fibonacci : Nat -> Nat
  | 0 => 0
  | 1 => 1
  | n + 2 => fibonacci (n + 1) + fibonacci n

def fibonacciSeq : Sequence := fun n => fibonacci n

/-- Constant coefficients for `F(n+2) - F(n+1) - F(n) = 0`. -/
def fibonacciP : Fin 3 -> Polynomial := fun j _ =>
  match j.val with
  | 0 => -1
  | 1 => -1
  | _ => 1

def fibonacciRecurrenceAt (n : Nat) : Bool :=
  fibonacciSeq (n + 2) == fibonacciSeq (n + 1) + fibonacciSeq n

/-- Fibonacci constant-coefficient P-recursion check for `n = 0..10`. -/
theorem fibonacci_precursive_check_0_to_10 :
    pRecurrenceHoldsOnRange 11 2 fibonacciP fibonacciSeq = true := by
  native_decide

theorem fibonacci_recurrence_check_0_to_10 :
    (List.range 11).all fibonacciRecurrenceAt = true := by
  native_decide

/-! ## Apéry numbers -/

/-- Apéry numbers generated by the classical second-order recurrence. -/
def apery : Nat -> Int
  | 0 => 1
  | 1 => 5
  | k + 2 =>
      let n : Int := k + 1
      (((2 * n + 1) * (17 * n ^ 2 + 17 * n + 5) * apery (k + 1)) -
          n ^ 3 * apery k) / (n + 1) ^ 3

def aperyOriginalRecurrenceAt (n : Nat) : Bool :=
  apery (n + 1) * ((n : Int) + 1) ^ 3 ==
    ((2 : Int) * (n : Int) + 1) *
        (17 * (n : Int) ^ 2 + 17 * (n : Int) + 5) * apery n -
      (n : Int) ^ 3 * apery (n - 1)

/--
Shifted coefficients for the standard P-recursive form:
`(n+2)^3 a(n+2) - (2n+3)(17(n+1)^2+17(n+1)+5)a(n+1)
  + (n+1)^3 a(n) = 0`.
-/
def aperyP : Fin 3 -> Polynomial := fun j n =>
  let x : Int := n
  match j.val with
  | 0 => (x + 1) ^ 3
  | 1 => -((2 * x + 3) * (17 * (x + 1) ^ 2 + 17 * (x + 1) + 5))
  | _ => (x + 2) ^ 3

theorem apery_values_0_to_3 :
    apery 0 = 1 ∧ apery 1 = 5 ∧ apery 2 = 73 ∧ apery 3 = 1445 := by
  native_decide

/-- Recurrence checks producing `a(2)` and `a(3)` from `a(0), a(1)`. -/
theorem apery_original_recurrence_check_1_to_2 :
    (List.range 2).all (fun k => aperyOriginalRecurrenceAt (k + 1)) = true := by
  native_decide

theorem apery_precursive_check_0_to_5 :
    pRecurrenceHoldsOnRange 6 2 aperyP apery = true := by
  native_decide

/-! ## Closure under addition: Catalan plus Fibonacci -/

def pointwiseAdd (a b : Sequence) : Sequence := fun n => a n + b n

def catalanPlusFibonacci : Sequence :=
  pointwiseAdd catalanSeq fibonacciSeq

/--
One P-recursive certificate for `C(n)+F(n)`, verified below by table check:
`p_0(n)s(n)+p_1(n)s(n+1)+p_2(n)s(n+2)+p_3(n)s(n+3)=0`.
-/
def catalanPlusFibonacciP : Fin 4 -> Polynomial := fun j n =>
  let x : Int := n
  match j.val with
  | 0 => 2 * (x + 1) * (2 * x + 1) * (11 * x + 24)
  | 1 => 3 * (11 * x ^ 3 + 35 * x ^ 2 + 38 * x + 16)
  | 2 => -(55 * x ^ 3 + 219 * x ^ 2 + 218 * x + 48)
  | _ => x * (x + 4) * (11 * x + 13)

theorem catalan_plus_fibonacci_values_0_to_7 :
    (List.range 8).map catalanPlusFibonacci =
      [1, 2, 3, 7, 17, 47, 140, 442] := by
  native_decide

/-- Addition closure example: a longer recurrence for `C(n)+F(n)`, checked on `n=0..10`. -/
theorem catalan_plus_fibonacci_precursive_check_0_to_10 :
    pRecurrenceHoldsOnRange 11 3 catalanPlusFibonacciP catalanPlusFibonacci = true := by
  native_decide

/-! ## Closure under Hadamard product -/

def pointwiseMul (a b : Sequence) : Sequence := fun n => a n * b n

def centralBinomialSeq : Sequence := fun n => Nat.choose (2 * n) n

def centralBinomialHadamardFibonacci : Sequence :=
  pointwiseMul centralBinomialSeq fibonacciSeq

/--
A P-recursive certificate for the Hadamard product `binom(2n,n) * F(n)`,
again used only as a finite table check here.
-/
def centralBinomialHadamardFibonacciP : Fin 3 -> Polynomial := fun j n =>
  let x : Int := n
  match j.val with
  | 0 => -4 * (2 * x + 1) * (2 * x + 3)
  | 1 => -2 * (x + 1) * (2 * x + 3)
  | _ => (x + 1) * (x + 2)

theorem central_binomial_hadamard_fibonacci_values_0_to_7 :
    (List.range 8).map centralBinomialHadamardFibonacci =
      [0, 2, 6, 40, 210, 1260, 7392, 44616] := by
  native_decide

theorem central_binomial_hadamard_fibonacci_precursive_check_0_to_10 :
    pRecurrenceHoldsOnRange 11 2 centralBinomialHadamardFibonacciP
      centralBinomialHadamardFibonacci = true := by
  native_decide

/-! ## Central Delannoy numbers -/

/-- Central Delannoy number `D(n) = sum_k binom(n,k)^2 2^k`. -/
def centralDelannoy (n : Nat) : Nat :=
  ∑ k ∈ Finset.range (n + 1), Nat.choose n k * Nat.choose n k * 2 ^ k

theorem central_delannoy_values_0_to_4 :
    centralDelannoy 0 = 1 ∧ centralDelannoy 1 = 3 ∧ centralDelannoy 2 = 13 ∧
      centralDelannoy 3 = 63 ∧ centralDelannoy 4 = 321 := by
  native_decide



structure DFactorialBudgetCertificate where
  primaryWindow : ℕ
  secondaryWindow : ℕ
  certificateBudgetWindow : ℕ
  slack : ℕ
deriving DecidableEq, Repr

def DFactorialBudgetCertificate.controlled
    (c : DFactorialBudgetCertificate) : Prop :=
  c.primaryWindow ≤ c.secondaryWindow + c.slack

def DFactorialBudgetCertificate.budgetControlled
    (c : DFactorialBudgetCertificate) : Prop :=
  c.certificateBudgetWindow ≤ c.primaryWindow + c.secondaryWindow + c.slack

def DFactorialBudgetCertificate.Ready
    (c : DFactorialBudgetCertificate) : Prop :=
  c.controlled ∧ c.budgetControlled

def DFactorialBudgetCertificate.size
    (c : DFactorialBudgetCertificate) : ℕ :=
  c.primaryWindow + c.secondaryWindow + c.slack

theorem dFactorial_budgetCertificate_le_size
    (c : DFactorialBudgetCertificate) (h : c.Ready) :
    c.certificateBudgetWindow ≤ c.size := by
  rcases h with ⟨_, hbudget⟩
  exact hbudget

def sampleDFactorialBudgetCertificate :
    DFactorialBudgetCertificate :=
  { primaryWindow := 3
    secondaryWindow := 5
    certificateBudgetWindow := 9
    slack := 1 }

example : sampleDFactorialBudgetCertificate.Ready := by
  constructor
  · norm_num [DFactorialBudgetCertificate.controlled,
      sampleDFactorialBudgetCertificate]
  · norm_num [DFactorialBudgetCertificate.budgetControlled,
      sampleDFactorialBudgetCertificate]

example :
    sampleDFactorialBudgetCertificate.certificateBudgetWindow ≤
      sampleDFactorialBudgetCertificate.size := by
  apply dFactorial_budgetCertificate_le_size
  constructor
  · norm_num [DFactorialBudgetCertificate.controlled,
      sampleDFactorialBudgetCertificate]
  · norm_num [DFactorialBudgetCertificate.budgetControlled,
      sampleDFactorialBudgetCertificate]

/-- Finite executable readiness audit for budget certificates. -/
theorem sampleBudgetCertificate_ready :
    sampleDFactorialBudgetCertificate.Ready := by
  constructor
  · norm_num [DFactorialBudgetCertificate.controlled,
      sampleDFactorialBudgetCertificate]
  · norm_num [DFactorialBudgetCertificate.budgetControlled,
      sampleDFactorialBudgetCertificate]

theorem sampleBudgetCertificate_le_size :
    sampleDFactorialBudgetCertificate.certificateBudgetWindow ≤
      sampleDFactorialBudgetCertificate.size := by
  exact sampleBudgetCertificate_ready.2

def budgetCertificateListReady (data : List DFactorialBudgetCertificate) : Bool :=
  data.all fun c =>
    c.primaryWindow ≤ c.secondaryWindow + c.slack &&
      c.certificateBudgetWindow ≤ c.primaryWindow + c.secondaryWindow + c.slack

theorem budgetCertificateList_readyWindow :
    budgetCertificateListReady
      [sampleDFactorialBudgetCertificate,
       { primaryWindow := 4, secondaryWindow := 6,
         certificateBudgetWindow := 11, slack := 1 }] = true := by
  unfold budgetCertificateListReady sampleDFactorialBudgetCertificate
  native_decide

end AnalyticCombinatorics.PartB.Ch5.DFactorial
